name: Firebase Hosting CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'vite.config.*'
      - '.env'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'vite.config.*'
      - '.env'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Inject .env from GitHub Secrets
        run: |
          echo "VITE_API_KEY=${{ secrets.VITE_API_KEY }}" >> .env
          echo "VITE_PROJECT_ID=${{ secrets.VITE_PROJECT_ID }}" >> .env
        # Add more VITE_ variables if needed

      - name: Build Vite project
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase (main)
        if: github.event_name == 'push'
        run: firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"

      - name: Deploy to Preview Channel (PR)
        if: github.event_name == 'pull_request'
        run: firebase hosting:channel:deploy pr-${{ github.event.pull_request.number }} --token "${{ secrets.FIREBASE_TOKEN }}"
